/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.anasoid.yunner.kotlin-application-conventions")
    id("test-report-aggregation")
    id("jacoco-report-aggregation")
    id("org.sonarqube") version "3.5.0.2730"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":yaml"))
    implementation(project(":core"))
}

application {
    // Define the main class for the application.
    mainClass.set("org.anasoid.yunner.app.AppKt")
}

tasks.check {
    dependsOn(tasks.named<TestReport>("testAggregateTestReport"))
    dependsOn(tasks.named<JacocoReport>("testCodeCoverageReport"))
}
